services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: postgres
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - 5432:5432
 
volumes:
    pgdata:
